include ../../winflags_dll
SUFFIXES=.obj .c .cpp

TAPOBJS=tapedoc.obj

%.obj: %.c
	@echo CC  $<
	@echo. >> error_out
	@echo CC  $< >> error_out
	@${CC} ${CFLAGS} $< >> error_out

%.obj: %.cpp
	@echo CXX $<
	@echo. >> error_out
	@echo CXX $< >> error_out
	@${CXX} ${CXXFLAGS} $< >> error_out

library: ${TAPOBJS}

$(TAPOBJS): Makefile.win

clean:
	@if exist *.obj del *.obj
	@if exist error_out del error_out
	@if exist *~ del *~
