#!/bin/bash
##############################################################################
# configure.ac -- Process this file with autoconf to produce configure
# Revision: $Id: make_64 289 2009-02-24 09:44:15Z awalther $
#
# Copyright (C) Andrea Walther, Andreas Kowarz
#
##############################################################################

export CC="gcc -m64"
export CXX="g++ -m64"
unset CPPFLAGS
unset CXXFLAGS
unset CFLAGS
unset LDFLAGS

if [ $? -eq 0 ] ; then
   INSTDIR="${HOME}/adolc_base"
   ./configure --prefix=${INSTDIR} --libdir=${INSTDIR}/lib64 "$@"
fi
make clean
if [ $? -eq 0 ] ; then
   make
fi
