include ../../../winflags_exa
SUFFIXES=.obj .cpp

OBJS=myclock.obj

%.obj: %.cpp
	@echo CXX $<
	@echo. >> error_out
	@echo CXX $< >> error_out
	@${CXX} ${CXXFLAGS} $< >> error_out

all: $(OBJS)
	@echo. >> error_out
	@echo "Built myclock.obj" >> error_out

myclock.obj: myclock.cpp myclock.h Makefile.win

clean:
	@if exist *.obj del *.obj
	@if exist myclock.obj del myclock.obj
	@if exist error_out del error_out

