include ../../winflags_dll
SUFFIXES=.obj .c .cpp

DRVOBJS=drivers.obj driversf.obj odedrivers.obj odedriversf.obj taylor.obj

%.obj: %.c
	@echo CC  $<
	@echo. >> error_out
	@echo CC  $< >> error_out
	@${CC} ${CFLAGS} $< >> error_out

library: ${DRVOBJS}

$(DRVOBJS): Makefile.win

clean:
	@if exist *.obj del *.obj
	@if exist error_out del error_out
	@if exist *~ del *~
